#FROM isif/hpfeeds:version1
FROM isif/hpfeeds:version1 


RUN echo 'cat > /opt/dionaea/etc/dionaea/ihandlers-enabled/hpfeeds.yaml
- name: hpfeeds\n\
  config:\n\
    # fqdn/ip and port of the hpfeeds broker\n\
    server: 103.19.110.157\n\
    port: 10000\n\
    ident: SGU-Dio-1-Alsut\n\
    secret: password1234\n\
    # dynip_resolve: enable to lookup the sensor ip through a webservice\n\
    #dynip_resolve: "http://canhazip.com/"\n\
    # Try to reconnect after N seconds if disconnected from hpfeeds broker\n\
    # reconnect_timeout: 10.0\n\
EOF\n'\
>> test.sh

#RUN apt update && apt-get install -y mongodb-clients
#RUN mongo
#RUN sed -i "s/bindIp: 127.0.0.1/bindIp: 0.0.0.0/g" /etc/mongod.conf.orig
#RUN cd mhn/scripts && ./install_hpfeeds.sh && ./install_mnemosyne.sh
#RUN supervisorctl && supervisorctl status hpfeeds-broker 
#&& ./install_mnemosyne.sh

#RUN mongo


#RUN supervisorctl status hpfeeds-broker && cd mhn/scripts && ./install_mnemosyne.sh
