#FROM isif/hpfeeds:version1
FROM isif/hpfeeds_mongodb_1804:version1 

#RUN cd mhn/scripts && ./install_hpfeeds.sh && ./install_mnemosyne.sh
#RUN supervisorctl && supervisorctl status hpfeeds-broker 
#&& ./install_mnemosyne.sh

#RUN mongo


#RUN supervisorctl status hpfeeds-broker && cd mhn/scripts && ./install_mnemosyne.sh
