#FROM isif/hpfeeds:version1
FROM isif/hpfeeds:version3 

RUN apt up
RUN mongo
#RUN sed -i "s/bindIp: 127.0.0.1/bindIp: 0.0.0.0/g" /etc/mongod.conf.orig
#RUN cd mhn/scripts && ./install_hpfeeds.sh && ./install_mnemosyne.sh
#RUN supervisorctl && supervisorctl status hpfeeds-broker 
#&& ./install_mnemosyne.sh

#RUN mongo


#RUN supervisorctl status hpfeeds-broker && cd mhn/scripts && ./install_mnemosyne.sh
